# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVMV Practice' do

  use_frameworks!

  pod 'Alamofire', '~> 4.0'
  pod 'PKHUD', '~> 5.0'
  pod 'SwiftyJSON'

end
